name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    # branches:
    #   - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test criate namespace
        uses: ./ # Uses an action in the root directory
        with:
          command: 'namespaces create back-testesteste$(echo -n $GITHUB_REF_NAME)'
          token: token-l8rt8:j6zlqwsprd5b9vrh9wwnbkzg85bsnxmjlmzq2qvfchxf6x2h2k5zsf
          context: c-m-b57b98j6:p-slt2w
          url: https://rancher.apps.oddie.com.br
