name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    # branches:
    #   - master

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Apropriate branch name without slash
        run: |
          echo "VERSION=$(echo -n $GITHUB_REF_NAME | sed -e 's|/|-|g' | sed -e 's|_|-|g')" >> $GITHUB_ENV
          echo "COMMAND=namespaces create back-$(echo -n $VERSION)" >> $GITHUB_ENV
          echo '::set-output name=COMMAND::namespaces create back-$VERSION'
          set
        id: namespace

      - name: Test criate namespace
        uses: ./ # Uses an action in the root directory
        with:
          command: $COMMAND
          token: token-h82zd:xpf45g9f6qv78swjvf79rkbwts4c4pqprjhpvmsvgx9zc6stnz7ctb
          context: c-m-b57b98j6:p-slt2w
          url: https://rancher.apps.oddie.com.br
